"""Add table files

Revision ID: 01aba1130e91
Revises: c3f3895e3de7
Create Date: 2025-01-22 21:57:29.520914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01aba1130e91'
down_revision: Union[str, None] = 'c3f3895e3de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('thumbnail_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'files', ['thumbnail_file_id'], ['id'])
    op.drop_column('articles', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('thumbnail', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'thumbnail_file_id')
    op.drop_table('files')
    # ### end Alembic commands ###
